baseurl = "/"
languageCode = "en-us"
title = "Tychobra"
#theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    top-learn = "/:filename/"
    top-about = "/:filename/"
    top-shiny = "/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
   name = "Blog"
   url = "/posts/"
   weight = 2
#[[menu.main]]
#    name = "About"
#    url = "/about/"
#    weight = 2
#[[menu.main]]
#    name = "Learn"
#    url = "/learn/"
#    weight = 3
#[[menu.main]]
#    name = "Tags"
#    url = "/tags/"
#    weight = 4
#[[menu.main]]
#    name = "Subscribe"
#    url = "/index.xml"

[params]
    #description = "A website built through Hugo and blogdown."
    footer = "Copyright &copy; Tychobra 2017"